### ISSUE TITLE
make this repo a PackageControl dependency

### ISSUE THREAD

**Issue by jrappen** [ihodev/sublime-file-icons#64]
To streamline the integration of this package's functionality with other theme / scheme packages, I suggest making this a [PackageControl dependency](https://packagecontrol.io/docs/dependencies).

That way any other theme / scheme package could add your repo as a dependency to `dependencies.json` within its root directory.

You would have to move your package within [wbond/package_control_channel](https://github.com/wbond/package_control_channel) from [`repository/z.json`](https://github.com/wbond/package_control_channel/blob/master/repository/z.json) to [`repository/dependencies.json`](https://github.com/wbond/package_control_channel/blob/master/repository/dependencies.json) though.

As you seem to be planning to rename this package for `version 3.0` anyway, you could do all of this is one step.

/cc @equinusocio @FichteFoll @kkga @MarkMichos @thinkpixellab @idleberg @ctf0 @theymaybecoders @jamiewilson @daylerees @Briles

**Comment by ihodev** [comment]
It was discussed [here](https://forum.sublimetext.com/t/sublime-text-3-file-icons-in-sidebar/21134).

I agree that adding this package as dependency will simplify its using by themes.  
However it will be able to override file icons for all themes. That's why it's bad solution.

E.g. 

1. You have installed `Seti UI` and `Material Theme` (which will have it as dependency)
2. If `Seti UI` is active – you'll see icons provided by the package, not by the theme, because Material Theme has that dependency.
3. If `Default` is active – the same story as with `Seti UI`
4. If `Material Theme` is active – you'll see the right icons.

The best solution with current ST implementation is to add `tmPreferences` to the packages those provide syntaxes. Because in other cases you'll see wrong or missing icon.

Currently I think that user have to know what and why he/she installs, that's why I provide it as package but not the dependency.

**Comment by FichteFoll** [comment]
As far as I understand and remember, at the moment this package relies on themes providing a special file that tells a plugin of this package to monkey-patch that theme into supporting sidebar icons. However, I believe that this is only required because the plugin generates a `.sublime-theme` file with the theme's name in its directory so that Sublime Text will additionally look into the icons provided by this package. Afaik, there is no other way to provide file icons.

If it was to be converted into a dependency (which would certainly make it easier for themes to support file icons "out of the box", i.e. immediately after installation), the following needed to be considered:

- Dependencies are not meant to support ST plugins. They *do*, but it's discouraged and support for this may be removed any time when dependencies are moved to a different directory (which will happen eventually, hopefully, because storing dependencies in the same folder as packages is a hack).

  Custom loader code via a `loader.py` file will likely still work, though, so that should be used.

- `loader.py` is only executed once and specifically *before* the actual package that is to be installed. (*Immediately* after the Default package, to be precise.) I suggest listening for changes with the `ignored_packages` list in `Preferences.sublime-settings` and re-scan packages for supported themes.

I do not know how this package interacts with themes that already supply theme icons themselves.

**Comment by jrappen** [comment]
@ihodev @FichteFoll I didn't know it would mess up other themes. In that case I guess you can disregard this idea and ..... I will close the issue.

---

@ihodev On another note, you maybe want to fix the link on the `package_control_channel` repo to point to this repo althought Github seems to redirect requests to this differently named repo on your new user account.

**Comment by jrappen** [comment]
Wouldn't publishing the dist files in a separate repo which one can integrate via git modules make sense then?

**Comment by FichteFoll** [comment]
No, because git submodules aren't included in zip-/tarball downloads from github and thus Package Control wouldn't be able to grab them.

**Comment by ihodev** [comment]
@jrappen 

> On another note, you maybe want to fix the link on the package_control_channel repo to point to this repo althought Github seems to redirect requests to this differently named repo on your new user account

Yeah, I'll fix that, I just want to do this with one pull request, when 3.0.0 will be ready.

> Wouldn't publishing the dist files in a separate repo which one can integrate via git modules make sense then?

@FichteFoll explained that. I think theme developers can provide simple `py` script to install this package right after theme installation and if the user doesn't want to use it he can remove it. I can create boilerplate script in the `Boxy Theme`. However I don't know if it's a good solution.

**Comment by jrappen** [comment]
Python will do then.
